# Generated by Django 5.0.1 on 2024-01-16 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
        ("ecomapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article",
                to="ecomapp.product",
            ),
        ),
    ]
